config/routes.rb
Loupe::Application.routes.draw do
	resources :services
	resources :disks do
		collection do
			get :raw
			get :rebuild
		end
	end
	
	root :to => "home#index"
end

app/models/disk.rb
class Disk < ActiveRecord::Base
	def percent
		((used/avaliable)*100).round(2)
	end
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/models/system.rb
class System < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery
	before_filter :check_on_god
	
	private
	
	def check_on_god
		god_status = System.find_by_name("God status")
		if god_status.value == "Check"
			unless `god status` =~ /Loupe:/ 
				flash[:warning] = "God was not running"
				`god -c #{RAILS_ROOT}/config/loupe.god`
				god_status.value = "Running"
				god_status.save
				#Put the new workers to work straight away
				Stalker.enqueue("disk-build")
				Stalker.enqueue("system-values")
				Stalker.enqueue("system-ram-build")
			else
				god_status.value = "Running"
				god_status.save
			end
		end
	end
end

app/controllers/disks_controller.rb
class DisksController < ApplicationController
	def index
		@disks = Disk.all
	end
	
	def rebuild
		@disks = Disk.all
		Stalker.enqueue("disk-build")
	end
	
	def show
		@disk = Disk.find_by_id(params[:id])
	end
	
	def raw
		@file = File.new("tmp/disk-h.txt","r")
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		Stalker.enqueue("system-ram-build")
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	def index
		@services = Service.all
	end
	
	def show
		@service = Service.find_by_id(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def jsit(*args)
		content_for(:jsit, javascript_include_tag(*args))
	end
end

app/helpers/disks_helper.rb
module DisksHelper
end

app/helpers/home_helper.rb
module HomeHelper
	def total_memory
		System.find_by_name("MemTotal").value.to_f + System.find_by_name("SwapTotal").value.to_f
	end
	
	def ram_total
		System.find_by_name("MemTotal").value.to_f
	end
	
	def swap_total
		System.find_by_name("SwapTotal").value.to_f
	end
	
	def ram_used
		ram_total - System.find_by_name("MemFree").value.to_f
	end
	
	def swap_used
		swap_total - System.find_by_name("SwapFree").value.to_f
	end
end

app/helpers/service_helper.rb
module ServiceHelper
end

app/views/disks/_disk_table.html.erb
<table class="table">
        <tr>             
          <th class="first">Disk</th>
          <th>Mount Point</th>
          <th>Size<% totalsize = 0 %>
          </th>
                    <th>Used<% totalused = 0 %></th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @disks.each do |disk| -%>
        <% barcolor = "#fdd" %>
        <% barcolor = "#ffc" if disk.percent < 85 %>
        <% barcolor = "#BBFFB6" if disk.percent < 45 %>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= disk.name %>
          </td>
          <td><%= disk.mountpoint %></td>
                    <td>
            <%= disk.avaliable.to_cscale %><%= disk.avaliable.cscale_unit %><% totalsize += disk.avaliable %>
          </td>
                    <td>
            <%= disk.used.to_cscale %><%= disk.used.cscale_unit %><% totalused += disk.used %>
          </td>
          <td class="last">
          	<table style="width:400px; border:1px #000 solid;">
          	<tr>
			<td width="<%= disk.percent %>%" style="background-color:<%= barcolor %>; text-align:center;"><%= disk.percent %>%</td>
			<td></td>
		</tr>
		</table>
          </td>
        </tr>          
        <% end -%>
        <tr>
        <th class="first"></th>
        <th>Totals</th>
        <th><%= totalsize.to_cscale %><%= totalsize.cscale_unit %></th>
        <th><%= totalused.to_cscale %><%= totalused.cscale_unit %></th>
        <th class="last"><table style="width:400px; border:1px #000 solid;">
          	<tr>
          	<% barcolor = "#fdd" %>
       		<% barcolor = "#ffc" if ((totalused/totalsize)*100) < 85 %>
        	<% barcolor = "#BBFFB6" if ((totalused/totalsize)*100) < 45 %>
			<td width="<%= ((totalused/totalsize)*100).round(2) %>%" style="background-color:<%= barcolor %>; text-align:center;"><%= ((totalused/totalsize)*100).round(2) %>%</td>
			<td></td>
		</tr>
		</table></th>
        </tr>
      </table>
            <div class="actions-bar wat-cf">
        <div class="actions">
        </div>      
      </div>

app/views/disks/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.disk.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :size, t("activerecord.attributes.disk.size", :default => "Size"), :class => :label %>
    <%= f.text_field :size, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :used, t("activerecord.attributes.disk.used", :default => "Used"), :class => :label %>
    <%= f.text_field :used, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :mountpoint, t("activerecord.attributes.disk.mountpoint", :default => "Mountpoint"), :class => :label %>
    <%= f.text_field :mountpoint, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), disks_path, :class => "button" %> 
</div>

app/views/disks/_sidebar.html.erb
<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/disks/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", disks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_disk_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_disk_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Disk</h2>
    <div class="inner">
      <%= form_for @disk, :url => disk_path(@disk), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/disks/index.html.erb
<% jsit "disk_view" %>
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "#{t("web-app-theme.list", :default => "List")}", disks_path  %></li>
      <li><%= link_to "df -h", raw_disks_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Disks</h2>
    <div class="inner" id="disk_table">
      <%= render 'disk_table' %>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/disks/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", disks_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_disk_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Disk</h2>
    <div class="inner">
      <%= form_for :disk, :url => disks_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/disks/raw.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", disks_path  %></li>
      <li class="active"><%= link_to "df -h", raw_disks_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">df -h</h2>
    <div class="inner">
	<% while (line = @file.gets) %>
		<%= line.gsub(/ /,"&nbsp;").html_safe %><br />
	<% end %>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/disks/rebuild.js.erb
$('#disk_table').html("<%= escape_javascript(render 'disk_table') %>");
var t=setTimeout("$.getScript('/disks/rebuild');",60000);

app/views/disks/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", disks_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_disk_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", disk_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.disk.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @disk.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.disk.size", :default => t("activerecord.labels.size", :default => "Size")) %>:</b>
          <%= @disk.size %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.disk.used", :default => t("activerecord.labels.used", :default => "Used")) %>:</b>
          <%= @disk.used %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.disk.mountpoint", :default => t("activerecord.labels.mountpoint", :default => "Mountpoint")) %>:</b>
          <%= @disk.mountpoint %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_disk_path(@disk), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), disk_path(@disk), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/home/_sidebar.html.erb
<div class="block notice">
  <h3>Lopue</h3>
  <div class="content">
    <p>Lopue is a server monitoring application written in ruby </p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="http://www.arcath.net" target="_BLANK">Arcath.net</a></li>
    <li><a href="http://github.com/Arcath/Loupe" target="_BLANK">Loupe repo</a></li>
  </ul>
</div>

app/views/home/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "Loupe", "#" %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= System.find_by_name("hostname").value %></h2>
    <div class="inner">
      Hostname: <%= System.find_by_name("hostname").value %><br />
      Uptime: <%= System.find_by_name("uptime").value %><br />
      Memory:
      <table width="100%" style="border:1px #000 solid;">
      <tr>
      	<td colspan="2" width="<%= ((ram_total/total_memory)*100).round %>%" style="background-color:#002134; color:#fff;">RAM <%= ram_total.to_cscale %><%= ram_total.cscale_unit %></td>
      	<td colspan="2" style="background-color:#002134; color:#fff;" width="<%= ((swap_total/total_memory)*100).round %>%">SWAP <%= swap_total.to_cscale %><%= swap_total.cscale_unit %></td>
      </tr>
      <tr>
      	<td width="<%= ((ram_used/total_memory)*100).round %>%" style="background-color:#002134; color:#fff;"><%= ram_used.to_cscale %><%= ram_used.cscale_unit %></td>
      	<td></td>
      	<td width="<%= ((swap_used/total_memory)*100).round %>%" style="background-color:#002134; color:#fff;"><%= swap_used.to_cscale %><%= swap_used.cscale_unit %></td>
      	<td></td>
      </tr>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>      
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Loupe</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/default/style", "web-app-theme/override", :cache => true %>
  <%= javascript_include_tag 'jquery', :cache => true %>
  <%= yield :jsit %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="/">Loupe :: <%= System.find_by_name("hostname").value %></a></h1>
      <div id="user-navigation">
        <ul class="wat-cf">
          <!--<li><a href="#"><%= t("web-app-theme.profile", :default => "Profile") %></a></li>
          <li><a href="#"><%= t("web-app-theme.settings", :default => "Settings") %></a></li>
          <li><a href="/logout" class="logout"><%= t("web-app-theme.logout", :default => "Logout") %></a></li>-->
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
        	<li><%= link_to "Home", root_path %></li>
        	<li><%= link_to "Services", services_path %></li>
        	<li><%= link_to "Disks", disks_path %></li>
        </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Loupe</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/services/_form.html.erb
  <div class="group">
    <%= f.label :name, t("activerecord.attributes.service.name", :default => "Name"), :class => :label %>
    <%= f.text_field :name, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>

  <div class="group">
    <%= f.label :status, t("activerecord.attributes.service.status", :default => "Status"), :class => :label %>
    <%= f.text_field :status, :class => 'text_field' %>
    <span class="description">Ex: a simple text</span>
  </div>
        
<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "#{t("web-app-theme.save", :default => "Save")}") %> <%= t("web-app-theme.save", :default => "Save") %>
  </button>  
  <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.cancel", :default => "Cancel")}") + " " + t("web-app-theme.cancel", :default => "Cancel"), services_path, :class => "button" %> 
</div>

app/views/services/_sidebar.html.erb
<div class="block notice">
  <h3>Services</h3>
  <div class="content">
    <p>Services Running on ...</p>
  </div>
</div>
<div class="block">
  <h3>Links</h3>
  <ul class="navigation">
    <li><a href="#">Link 1</a></li>
    <li><a href="#">Link 2</a></li>
  </ul>
</div>

app/views/services/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", services_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_service_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.edit", :default => "Edit")}", edit_service_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.edit", :default => "Edit") %> Service</h2>
    <div class="inner">
      <%= form_for @service, :url => service_path(@service), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/services/index.html.erb
<style type="text/css">
.oddrunning{
	background-color:#bbffb6;
}

.evenrunning{
	background-color:#bbffc7;
}

.oddoffline{
	background-color:#fdd;
}

.evenoffline{
	background-color:#fbb;
}
</style>

<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "All Services", services_path  %></li>
      <li><%= link_to "Offline Services", "#" %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title"><%= t("web-app-theme.all", :default => "All")  %> Services</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">Service</th>
                    <th>
            Status
          </th>
          <th class="last">&nbsp;</th>
        </tr>
        <% @services.each do |service| -%>
        <tr class="<%= cycle("odd", "even") %><%= service.status %>">
          <td>
            <%= service.name %>
          </td>
                    <td>
            <%= service.status %>
          </td>
          <td class="last">

          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/services/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", services_path  %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_service_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= t("web-app-theme.new", :default => "New")%>  Service</h2>
    <div class="inner">
      <%= form_for :service, :url => services_path, :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/services/show.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "#{t("web-app-theme.list", :default => "List")}", services_path  %></li>
      <li><%= link_to "#{t("web-app-theme.new", :default => "New")}", new_service_path %></li>
      <li class="active"><%= link_to "#{t("web-app-theme.show", :default => "Show")}", service_path %></li>
    </ul>
  </div>          
  <div class="content">
    <div class="inner">
      
        <p>
          <b><%= t("activerecord.attributes.service.name", :default => t("activerecord.labels.name", :default => "Name")) %>:</b>
          <%= @service.name %>
        </p>

        <p>
          <b><%= t("activerecord.attributes.service.status", :default => t("activerecord.labels.status", :default => "Status")) %>:</b>
          <%= @service.status %>
        </p>
      <div class="wat-cf">
        <%= link_to image_tag("web-app-theme/icons/application_edit.png", :alt => "#{t("web-app-theme.edit", :default=> "Edit")}") + " " + t("web-app-theme.edit", :default=> "Edit"), edit_service_path(@service), :class => "button" %> 
        <%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "#{t("web-app-theme.delete", :default=> "Delete")}") + " " + t("web-app-theme.delete", :default => "Delete"), service_path(@service), :method => "delete", :class => "button", :confirm => "#{t("web-app-theme.confirm", :default => "Are you sure?")}" %>
      </div>      
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>